# Generated by Django 5.2.5 on 2025-08-19 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coordinator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='galary',
            name='galary_type',
            field=models.CharField(default='', max_length=255),
        ),
    ]
