# Generated by Django 5.2.5 on 2025-08-19 04:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Coordinator', '0002_galary_galary_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Galary',
            new_name='Gallery',
        ),
        migrations.RenameField(
            model_name='gallery',
            old_name='galary_type',
            new_name='gallery_type',
        ),
    ]
