# Generated by Django 5.2.5 on 2025-09-11 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coordinator', '0006_alter_profile_address_alter_profile_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcq',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mcq',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='mcq',
            name='mcq_duration',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
