# Generated by Django 5.2.5 on 2025-09-16 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coordinator', '0007_mcq_date_mcq_is_active_mcq_mcq_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='event_mcq',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='Coordinator.mcq'),
            preserve_default=False,
        ),
    ]
