# Generated by Django 5.2.5 on 2025-09-16 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coordinator', '0010_alter_events_event_mcq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='event_mcq',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='Coordinator.mcq'),
        ),
    ]
