# Generated by Django 5.2.5 on 2025-09-16 09:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Coordinator', '0013_eveentregister'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EveentRegister',
            new_name='EventRegister',
        ),
    ]
