# Generated by Django 5.2.6 on 2025-10-01 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coordinator', '0014_rename_eveentregister_eventregister'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='admission_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='branch',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='registration_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='year',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
