# Generated by Django 5.2.6 on 2025-10-01 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coordinator', '0015_profile_admission_no_profile_branch_profile_dob_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
