# Generated by Django 5.2.6 on 2025-10-08 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coordinator', '0018_events_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregister',
            name='branch',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='eventregister',
            name='project_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventregister',
            name='project_members',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventregister',
            name='project_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
