# Generated by Django 5.2.6 on 2025-10-09 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coordinator', '0020_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='date',
            field=models.CharField(max_length=255),
            preserve_default=False,
        ),
    ]
