# Generated by Django 5.2.6 on 2025-10-09 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Coordinator', '0021_notification_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
