# Generated by Django 5.2.5 on 2025-10-13 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coordinator', '0023_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cgpa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.CreateModel(
            name='StudentSGPA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(choices=[('1', 'Semester 1'), ('2', 'Semester 2'), ('3', 'Semester 3'), ('4', 'Semester 4'), ('5', 'Semester 5'), ('6', 'Semester 6')], max_length=1)),
                ('academic_year', models.CharField(max_length=20)),
                ('subject_1_name', models.CharField(blank=True, max_length=100)),
                ('subject_1_grade', models.CharField(blank=True, choices=[('S', 'S (10)'), ('A', 'A (9)'), ('B', 'B (8)'), ('C', 'C (7)'), ('D', 'D (6)'), ('E', 'E (5)'), ('F', 'F (0)')], max_length=1)),
                ('subject_2_name', models.CharField(blank=True, max_length=100)),
                ('subject_2_grade', models.CharField(blank=True, choices=[('S', 'S (10)'), ('A', 'A (9)'), ('B', 'B (8)'), ('C', 'C (7)'), ('D', 'D (6)'), ('E', 'E (5)'), ('F', 'F (0)')], max_length=1)),
                ('subject_3_name', models.CharField(blank=True, max_length=100)),
                ('subject_3_grade', models.CharField(blank=True, choices=[('S', 'S (10)'), ('A', 'A (9)'), ('B', 'B (8)'), ('C', 'C (7)'), ('D', 'D (6)'), ('E', 'E (5)'), ('F', 'F (0)')], max_length=1)),
                ('subject_4_name', models.CharField(blank=True, max_length=100)),
                ('subject_4_grade', models.CharField(blank=True, choices=[('S', 'S (10)'), ('A', 'A (9)'), ('B', 'B (8)'), ('C', 'C (7)'), ('D', 'D (6)'), ('E', 'E (5)'), ('F', 'F (0)')], max_length=1)),
                ('subject_5_name', models.CharField(blank=True, max_length=100)),
                ('subject_5_grade', models.CharField(blank=True, choices=[('S', 'S (10)'), ('A', 'A (9)'), ('B', 'B (8)'), ('C', 'C (7)'), ('D', 'D (6)'), ('E', 'E (5)'), ('F', 'F (0)')], max_length=1)),
                ('subject_6_name', models.CharField(blank=True, max_length=100)),
                ('subject_6_grade', models.CharField(blank=True, choices=[('S', 'S (10)'), ('A', 'A (9)'), ('B', 'B (8)'), ('C', 'C (7)'), ('D', 'D (6)'), ('E', 'E (5)'), ('F', 'F (0)')], max_length=1)),
                ('sgpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sgpa_records', to='Coordinator.profile')),
            ],
            options={
                'ordering': ['semester'],
                'unique_together': {('student', 'semester')},
            },
        ),
    ]
