# Generated by Django 5.2.5 on 2025-10-22 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coordinator', '0024_profile_cgpa_studentsgpa'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsgpa',
            name='subject_10_grade',
            field=models.CharField(blank=True, choices=[('S', 'S (10)'), ('A', 'A (9)'), ('B', 'B (8)'), ('C', 'C (7)'), ('D', 'D (6)'), ('E', 'E (5)'), ('F', 'F (0)')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='studentsgpa',
            name='subject_10_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentsgpa',
            name='subject_7_grade',
            field=models.CharField(choices=[('S', 'S (10)'), ('A', 'A (9)'), ('B', 'B (8)'), ('C', 'C (7)'), ('D', 'D (6)'), ('E', 'E (5)'), ('F', 'F (0)')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentsgpa',
            name='subject_7_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentsgpa',
            name='subject_8_grade',
            field=models.CharField(choices=[('S', 'S (10)'), ('A', 'A (9)'), ('B', 'B (8)'), ('C', 'C (7)'), ('D', 'D (6)'), ('E', 'E (5)'), ('F', 'F (0)')], default='s', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentsgpa',
            name='subject_8_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentsgpa',
            name='subject_9_grade',
            field=models.CharField(blank=True, choices=[('S', 'S (10)'), ('A', 'A (9)'), ('B', 'B (8)'), ('C', 'C (7)'), ('D', 'D (6)'), ('E', 'E (5)'), ('F', 'F (0)')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='studentsgpa',
            name='subject_9_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentsgpa',
            name='subject_1_grade',
            field=models.CharField(choices=[('S', 'S (10)'), ('A', 'A (9)'), ('B', 'B (8)'), ('C', 'C (7)'), ('D', 'D (6)'), ('E', 'E (5)'), ('F', 'F (0)')], max_length=1),
        ),
        migrations.AlterField(
            model_name='studentsgpa',
            name='subject_1_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='studentsgpa',
            name='subject_2_grade',
            field=models.CharField(choices=[('S', 'S (10)'), ('A', 'A (9)'), ('B', 'B (8)'), ('C', 'C (7)'), ('D', 'D (6)'), ('E', 'E (5)'), ('F', 'F (0)')], max_length=1),
        ),
        migrations.AlterField(
            model_name='studentsgpa',
            name='subject_2_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='studentsgpa',
            name='subject_3_grade',
            field=models.CharField(choices=[('S', 'S (10)'), ('A', 'A (9)'), ('B', 'B (8)'), ('C', 'C (7)'), ('D', 'D (6)'), ('E', 'E (5)'), ('F', 'F (0)')], max_length=1),
        ),
        migrations.AlterField(
            model_name='studentsgpa',
            name='subject_3_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='studentsgpa',
            name='subject_4_grade',
            field=models.CharField(choices=[('S', 'S (10)'), ('A', 'A (9)'), ('B', 'B (8)'), ('C', 'C (7)'), ('D', 'D (6)'), ('E', 'E (5)'), ('F', 'F (0)')], max_length=1),
        ),
        migrations.AlterField(
            model_name='studentsgpa',
            name='subject_4_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='studentsgpa',
            name='subject_5_grade',
            field=models.CharField(choices=[('S', 'S (10)'), ('A', 'A (9)'), ('B', 'B (8)'), ('C', 'C (7)'), ('D', 'D (6)'), ('E', 'E (5)'), ('F', 'F (0)')], max_length=1),
        ),
        migrations.AlterField(
            model_name='studentsgpa',
            name='subject_5_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='studentsgpa',
            name='subject_6_grade',
            field=models.CharField(choices=[('S', 'S (10)'), ('A', 'A (9)'), ('B', 'B (8)'), ('C', 'C (7)'), ('D', 'D (6)'), ('E', 'E (5)'), ('F', 'F (0)')], max_length=1),
        ),
        migrations.AlterField(
            model_name='studentsgpa',
            name='subject_6_name',
            field=models.CharField(max_length=100),
        ),
    ]
