# Generated by Django 5.2.5 on 2025-10-22 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coordinator', '0025_studentsgpa_subject_10_grade_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentsgpa',
            name='academic_year',
        ),
        migrations.AddField(
            model_name='studentsgpa',
            name='subject_1_credits',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentsgpa',
            name='semester',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='studentsgpa',
            name='subject_10_grade',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='studentsgpa',
            name='subject_10_name',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='studentsgpa',
            name='subject_1_grade',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='studentsgpa',
            name='subject_1_name',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studentsgpa',
            name='subject_2_grade',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studentsgpa',
            name='subject_2_name',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studentsgpa',
            name='subject_3_grade',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studentsgpa',
            name='subject_3_name',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studentsgpa',
            name='subject_4_grade',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studentsgpa',
            name='subject_4_name',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studentsgpa',
            name='subject_5_grade',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studentsgpa',
            name='subject_5_name',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studentsgpa',
            name='subject_6_grade',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studentsgpa',
            name='subject_6_name',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studentsgpa',
            name='subject_7_grade',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studentsgpa',
            name='subject_7_name',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studentsgpa',
            name='subject_8_grade',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studentsgpa',
            name='subject_8_name',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studentsgpa',
            name='subject_9_grade',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='studentsgpa',
            name='subject_9_name',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
