# Generated by Django 5.2.5 on 2025-10-22 10:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coordinator', '0026_remove_studentsgpa_academic_year_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentsgpa',
            options={},
        ),
        migrations.RenameField(
            model_name='studentsgpa',
            old_name='subject_1_name',
            new_name='total_credits',
        ),
        migrations.AlterUniqueTogether(
            name='studentsgpa',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=255)),
                ('subject_code', models.CharField(max_length=255)),
                ('subject_credits', models.PositiveIntegerField()),
                ('subject_grade', models.CharField(blank=True, max_length=2, null=True)),
                ('grade_point', models.FloatField(blank=True, null=True)),
                ('student_sgpa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='Coordinator.studentsgpa')),
            ],
        ),
        migrations.RemoveField(
            model_name='studentsgpa',
            name='subject_10_grade',
        ),
        migrations.RemoveField(
            model_name='studentsgpa',
            name='subject_10_name',
        ),
        migrations.RemoveField(
            model_name='studentsgpa',
            name='subject_1_credits',
        ),
        migrations.RemoveField(
            model_name='studentsgpa',
            name='subject_1_grade',
        ),
        migrations.RemoveField(
            model_name='studentsgpa',
            name='subject_2_grade',
        ),
        migrations.RemoveField(
            model_name='studentsgpa',
            name='subject_2_name',
        ),
        migrations.RemoveField(
            model_name='studentsgpa',
            name='subject_3_grade',
        ),
        migrations.RemoveField(
            model_name='studentsgpa',
            name='subject_3_name',
        ),
        migrations.RemoveField(
            model_name='studentsgpa',
            name='subject_4_grade',
        ),
        migrations.RemoveField(
            model_name='studentsgpa',
            name='subject_4_name',
        ),
        migrations.RemoveField(
            model_name='studentsgpa',
            name='subject_5_grade',
        ),
        migrations.RemoveField(
            model_name='studentsgpa',
            name='subject_5_name',
        ),
        migrations.RemoveField(
            model_name='studentsgpa',
            name='subject_6_grade',
        ),
        migrations.RemoveField(
            model_name='studentsgpa',
            name='subject_6_name',
        ),
        migrations.RemoveField(
            model_name='studentsgpa',
            name='subject_7_grade',
        ),
        migrations.RemoveField(
            model_name='studentsgpa',
            name='subject_7_name',
        ),
        migrations.RemoveField(
            model_name='studentsgpa',
            name='subject_8_grade',
        ),
        migrations.RemoveField(
            model_name='studentsgpa',
            name='subject_8_name',
        ),
        migrations.RemoveField(
            model_name='studentsgpa',
            name='subject_9_grade',
        ),
        migrations.RemoveField(
            model_name='studentsgpa',
            name='subject_9_name',
        ),
    ]
