# Generated by Django 5.2.5 on 2026-03-19 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Coordinator', '0029_eventimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventImage',
        ),
    ]
