# Generated by Django 5.2.4 on 2025-08-04 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CompanyDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone", models.CharField(max_length=100, unique=True)),
                ("location", models.CharField(max_length=100)),
                ("industry_type", models.CharField(max_length=100)),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True, null=True, upload_to="CompanyProfilePicture"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JobDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=100)),
                ("salary", models.FloatField()),
                ("location", models.CharField(max_length=100)),
                ("industry_type", models.CharField(max_length=100)),
                ("cgpa_threshold", models.FloatField(blank=True, null=True)),
                ("job_type", models.CharField(max_length=100)),
                ("job_mode", models.CharField(max_length=100)),
                ("resume", models.FileField(upload_to="Resume")),
                ("date_posted", models.DateField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="company.companydetails",
                    ),
                ),
            ],
        ),
    ]
