# Generated by Django 5.2.4 on 2025-08-06 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0004_alter_jobdetails_date_posted_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jobdetails",
            name="resume",
        ),
    ]
