# Generated by Django 5.2.5 on 2025-08-13 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_rename_is_active_jobapplication_confirm_info'),
        ('student', '0003_studentdetails_is_resume_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to='student.studentdetails'),
        ),
    ]
