# Generated by Django 5.2.10 on 2026-02-16 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_donation_assigned_ngo_donation_assigned_volunteer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='address',
            field=models.TextField(default='No address provided', help_text='Full pickup address'),
            preserve_default=False,
        ),
    ]
