# Generated by Django 5.2.10 on 2026-02-17 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0003_donation_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='delivery_otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='pickup_otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
