# Generated by Django 5.2.5 on 2026-02-17 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resorts', '0002_remove_booking_room_booking_guests_count_booking_otp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='capacity',
            field=models.PositiveIntegerField(default=2),
        ),
    ]
