# Generated by Django 5.2.5 on 2026-02-18 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resorts', '0003_room_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='resort',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
