# Generated by Django 5.2.5 on 2026-02-18 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resorts', '0005_resort_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('owner', 'Owner'), ('customer', 'Customer')], default='customer', max_length=10),
        ),
    ]
