# Generated by Django 5.2.5 on 2026-02-18 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resorts', '0005_resort_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='ar_model',
            field=models.FileField(blank=True, null=True, upload_to='ar_models/'),
        ),
    ]
