# Generated by Django 5.2.5 on 2026-02-18 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resorts', '0006_alter_user_role'),
        ('resorts', '0006_razorpay_and_ar_model'),
    ]

    operations = [
    ]
