# Generated by Django 5.2.5 on 2026-02-19 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resorts', '0008_resort_is_active_resortreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='resort',
            name='category',
            field=models.CharField(choices=[('Beach', 'Beach'), ('Mountain', 'Mountain'), ('Urban', 'Urban')], default='Beach', max_length=20),
        ),
    ]
