# Generated by Django 5.2.5 on 2026-02-19 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resorts', '0010_resortreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='resort',
            name='ar_model',
            field=models.FileField(blank=True, null=True, upload_to='resort_ar_models/'),
        ),
    ]
