# Generated by Django 5.2.5 on 2026-02-19 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resorts', '0011_resort_ar_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='otp',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
