# Generated by Django 5.2.5 on 2025-08-12 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_studentdetails_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdetails',
            name='is_resume_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentdetails',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='StudentResume'),
        ),
    ]
