# Generated by Django 5.2.10 on 2026-02-01 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, help_text='Booking price (copied from vendor)', max_digits=10)),
                ('status', models.CharField(choices=[('Booked', 'Booked')], default='Booked', help_text='Booking status', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(help_text='Event for this booking', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='events.event')),
                ('vendor', models.ForeignKey(help_text='Vendor being booked', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='vendors.vendor')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('event', 'vendor')},
            },
        ),
    ]
