# Generated by Django 5.2.9 on 2026-02-05 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='comment_warning_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='post_warning_count',
            field=models.IntegerField(default=0),
        ),
    ]
