# Generated by Django 5.2.4 on 2025-08-04 03:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone", models.CharField(max_length=100, unique=True)),
                ("address", models.CharField(max_length=100)),
                ("date_of_birth", models.DateField()),
                ("gender", models.CharField(max_length=100)),
                ("blood_group", models.CharField(max_length=100)),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True, null=True, upload_to="StudentProfilePicture"
                    ),
                ),
                ("course", models.CharField(max_length=100)),
                ("branch", models.CharField(max_length=100)),
                ("year", models.CharField(max_length=100)),
                ("sem", models.CharField(max_length=100)),
                ("roll_no", models.CharField(max_length=100)),
                ("reg_no", models.CharField(max_length=100, unique=True)),
                ("cgpa", models.FloatField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
