# Generated by Django 5.2.5 on 2025-08-14 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_studentdetails_is_resume_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetails',
            name='is_resume_approved',
            field=models.BooleanField(),
        ),
    ]
