# Generated by Django 5.2.5 on 2025-08-18 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_alter_studentdetails_is_resume_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetails',
            name='is_resume_approved',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
