# Generated by Django 5.2.1 on 2025-06-08 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0003_attendance_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
