# Generated by Django 5.2.1 on 2025-06-20 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0004_alter_attendance_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attendance",
            name="time_slot",
        ),
    ]
