# Generated by Django 5.2.5 on 2026-01-04 05:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
        ('memberships', '0001_initial'),
        ('trainers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('address', models.TextField()),
                ('emergency_contact_name', models.CharField(max_length=100)),
                ('emergency_contact_phone', models.CharField(max_length=15)),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3, null=True)),
                ('medical_notes', models.TextField(blank=True, help_text='Any medical conditions or allergies', null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, help_text='Height in cm', max_digits=5, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='Weight in kg', max_digits=5, null=True)),
                ('fitness_goal', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membership_request', to=settings.AUTH_USER_MODEL)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_membership_requests', to=settings.AUTH_USER_MODEL)),
                ('selected_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='memberships.membershipplan')),
            ],
            options={
                'verbose_name': 'Membership Request',
                'verbose_name_plural': 'Membership Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_specialization', models.CharField(choices=[('strength', 'Strength Training'), ('cardio', 'Cardio'), ('yoga', 'Yoga'), ('pilates', 'Pilates'), ('crossfit', 'CrossFit'), ('martial_arts', 'Martial Arts'), ('zumba', 'Zumba'), ('general', 'General Fitness')], max_length=20)),
                ('sessions_per_week', models.IntegerField(choices=[(1, '1 Session'), (2, '2 Sessions'), (3, '3 Sessions'), (4, '4 Sessions'), (5, '5+ Sessions')], default=2)),
                ('preferred_time', models.CharField(choices=[('morning', 'Morning (6 AM - 12 PM)'), ('afternoon', 'Afternoon (12 PM - 6 PM)'), ('evening', 'Evening (6 PM - 10 PM)')], max_length=20)),
                ('fitness_goals', models.TextField(help_text='What do you want to achieve with personal training?')),
                ('additional_notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_trainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_requests', to='trainers.trainer')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainer_requests', to='members.member')),
                ('preferred_trainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='trainers.trainer')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_trainer_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trainer Request',
                'verbose_name_plural': 'Trainer Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
