# Generated by Django 5.2.4 on 2025-08-06 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0002_companydetails_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobdetails",
            name="date_posted",
            field=models.DateField(auto_created=True),
        ),
    ]
