# Generated by Django 5.2.4 on 2025-08-06 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0003_alter_jobdetails_date_posted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobdetails",
            name="date_posted",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="jobdetails",
            name="description",
            field=models.TextField(),
        ),
    ]
