# Generated by Django 5.2.5 on 2025-08-13 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_jobapplication'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobapplication',
            old_name='is_active',
            new_name='confirm_info',
        ),
    ]
