# Generated by Django 5.2.11 on 2026-02-28 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('ADVANCE', 'Advance Payment'), ('BALANCE', 'Balance Payment'), ('FULL', 'Full Payment')], max_length=20),
        ),
    ]
