# Generated by Django 5.2.11 on 2026-02-10 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('text', models.TextField()),
                ('subject', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('is_fake', models.BooleanField(default=False)),
            ],
        ),
    ]
