# Generated by Django 5.2.12 on 2026-03-13 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_jobseekerprofile_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='is_fake',
            field=models.BooleanField(default=False),
        ),
    ]
