# Generated by Django 5.2.5 on 2026-03-19 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_jobpost_is_fake'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpost',
            name='is_fake',
        ),
    ]
