# Generated by Django 5.2.10 on 2026-02-13 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_serviceprovider_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceprovider',
            name='category',
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='categories',
            field=models.ManyToManyField(related_name='providers', to='services.category'),
        ),
    ]
