# Generated by Django 5.2.10 on 2026-02-13 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_review_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceprovider',
            name='completion_rate',
        ),
        migrations.RemoveField(
            model_name='serviceprovider',
            name='on_time_rate',
        ),
        migrations.AddField(
            model_name='review',
            name='was_on_time',
            field=models.BooleanField(default=True),
        ),
    ]
