# Generated by Django 5.2.11 on 2026-02-14 04:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_rename_location_userprofile_location_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='accepted_requests',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='cancelled_by_provider',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='no_show_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='total_requests',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='budget_tolerance',
            field=models.CharField(choices=[('low', 'Budget Focused'), ('mid', 'Value for Money'), ('high', 'Premium Only')], default='mid', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='distance_tolerance_km',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='favorite_categories',
            field=models.ManyToManyField(blank=True, related_name='interested_users', to='services.category'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='quality_priority',
            field=models.BooleanField(default=True, help_text='Prefer high rating over low cost'),
        ),
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_type', models.CharField(choices=[('LATE', 'Late Arrival'), ('QUALITY', 'Poor Service Quality'), ('BEHAVIOR', 'Unprofessional Behavior'), ('COST', 'Price Discrepancy'), ('OTHER', 'Other')], max_length=20)),
                ('description', models.TextField()),
                ('evidence', models.ImageField(blank=True, null=True, upload_to='disputes/')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_REVIEW', 'In Review'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], default='OPEN', max_length=20)),
                ('resolution_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dispute', to='services.booking')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
