# Generated by Django 5.2.11 on 2026-03-03 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_serviceprovider_accepted_requests_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceprovider',
            name='bio_ta',
        ),
        migrations.RemoveField(
            model_name='serviceprovider',
            name='name_ta',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='preferred_language',
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
