[project]
name = "placement"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django>=5.2.4",
    "faker>=37.5.3",
    "opencv-python>=4.12.0.88",
    "pillow>=11.3.0",
]
