# Generated by Django 5.2.5 on 2025-10-10 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_jobapplication_job_seeker'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='skills',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
    ]
