# Generated by Django 5.2.5 on 2025-12-11 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_jobpost_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
