# Generated by Django 5.2.10 on 2026-02-01 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Vendor name', max_length=200)),
                ('category', models.CharField(choices=[('Caterer', 'Caterer'), ('Decorator', 'Decorator'), ('Photographer', 'Photographer')], help_text='Vendor service category', max_length=50)),
                ('price', models.DecimalField(decimal_places=2, help_text='Vendor service price', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
    ]
