# Generated by Django 5.2.10 on 2026-02-20 06:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_is_completed_assignmentstatus_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='mentors',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'mentor'}, related_name='allocated_domains', to=settings.AUTH_USER_MODEL),
        ),
    ]
