# Generated by Django 5.2.10 on 2026-02-20 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_domain_mentors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='career_goal',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='interest',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='domain_joined_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='approval_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('MENTOR_APPROVED', 'Mentor Approved'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='preferred_domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrolled_students', to='core.domain'),
        ),
    ]
