# Generated by Django 5.2.11 on 2026-02-20 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_studentprofile_career_goal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizresult',
            name='quiz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='core.quiz'),
        ),
        migrations.AlterUniqueTogether(
            name='quizresult',
            unique_together={('student', 'quiz')},
        ),
    ]
