# Generated by Django 5.2.10 on 2026-02-21 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_quizresult_quiz_alter_quizresult_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='quizresult',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='quizresult',
            name='quiz',
        ),
    ]
