# Generated by Django 5.2.11 on 2026-02-22 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_domain_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('mentor', 'Mentor'), ('hod', 'HOD'), ('alumni', 'Alumni')], max_length=10),
        ),
    ]
