# Generated by Django 5.2.11 on 2026-02-22 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alumni_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
