# Generated by Django 5.2.10 on 2026-03-08 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_topicrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topicrequest',
            name='description',
        ),
    ]
