# Generated by Django 5.2.10 on 2026-03-08 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_topicrequest_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('mentor', 'Mentor'), ('hod', 'HOD'), ('alumni', 'Alumni'), ('rep', 'Student Representative')], max_length=10),
        ),
    ]
