# Generated by Django 5.2.10 on 2026-03-08 16:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='student_reps',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'rep'}, related_name='rep_domains', to=settings.AUTH_USER_MODEL),
        ),
    ]
