# Generated by Django 5.2.1 on 2025-06-12 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_alter_payment_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="receipt",
            name="student",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="receipts",
                to="app.student",
            ),
            preserve_default=False,
        ),
    ]
