# Generated by Django 5.2.1 on 2025-06-14 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_receipt_student"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="payment_completed",
        ),
        migrations.AddField(
            model_name="student",
            name="certificate_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
