# Generated by Django 5.2.1 on 2025-06-25 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_transaction_account_balance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="timestamp",
            field=models.DateTimeField(),
        ),
    ]
