# Generated by Django 5.2.1 on 2025-09-25 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_company_contacts_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_contacts',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company_contacts',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company_contacts',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company_contacts',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company_contacts',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='service_point_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_points', models.CharField(max_length=500)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_point', to='app.website_services')),
            ],
        ),
        migrations.DeleteModel(
            name='service_detail',
        ),
    ]
