# Generated by Django 5.2.1 on 2025-09-25 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_company_contacts_address_company_contacts_facebook_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='website_services',
            name='key_points',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='service_point_list',
        ),
    ]
