# Generated by Django 5.2.1 on 2025-09-25 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_website_services_key_points_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='website_course',
            name='course_level',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='website_course',
            name='course_price',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
