# Generated by Django 5.2.1 on 2025-09-25 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_website_course_course_level_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='website_course',
            old_name='course_level',
            new_name='course_difficulty',
        ),
    ]
