# Generated by Django 5.2.1 on 2025-09-25 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_rename_course_level_website_course_course_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='website_gallery',
            name='gallery_title',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
