# Generated by Django 5.2.1 on 2025-09-25 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_website_gallery_gallery_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company_contacts',
            old_name='phone',
            new_name='phone1',
        ),
        migrations.AddField(
            model_name='company_contacts',
            name='phone2',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
