# Generated by Django 5.2.1 on 2025-09-26 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_rename_phone_company_contacts_phone1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website_services',
            name='key_points',
            field=models.JSONField(),
        ),
    ]
