# Generated by Django 5.2.6 on 2025-09-26 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_alter_website_services_key_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_contacts',
            name='map_embed_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
