# Generated by Django 5.2.6 on 2025-09-27 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_company_contacts_map_embed_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_contacts',
            name='youtube',
            field=models.URLField(blank=True, null=True),
        ),
    ]
