# Generated by Django 5.2.6 on 2025-10-03 11:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_company_contacts_youtube'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='company_career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=500)),
                ('application_Deadline', models.DateField()),
                ('job_type', models.CharField(max_length=500)),
                ('experience', models.CharField(max_length=500)),
                ('key_responsibilities', models.JSONField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
