# Generated by Django 5.2.6 on 2025-10-03 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_company_career'),
    ]

    operations = [
        migrations.CreateModel(
            name='company_applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=500)),
                ('last_name', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.PositiveBigIntegerField()),
                ('experience', models.CharField(max_length=500)),
                ('current_company', models.CharField(blank=True, max_length=500, null=True)),
                ('resume', models.FileField(upload_to='ApplicantResume')),
                ('cover_letter', models.TextField(blank=True, null=True)),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicant', to='app.company_career')),
            ],
        ),
    ]
