# Generated by Django 5.2.10 on 2026-02-01 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Guest name', max_length=200)),
                ('contact', models.CharField(help_text='Guest contact information (phone/email)', max_length=100)),
                ('category', models.CharField(choices=[('Family', 'Family'), ('Friend', 'Friend'), ('VIP', 'VIP')], help_text='Guest category', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(help_text='Event this guest is invited to', on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='events.event')),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
    ]
