# Generated by Django 5.2.5 on 2026-01-28 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientprofile',
            old_name='mobile_number',
            new_name='whatsapp_number',
        ),
    ]
