# Generated by Django 5.2.5 on 2026-01-28 09:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_testbooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='labassistant',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='labassistant',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='labassistant',
            name='lab_name',
            field=models.CharField(default='Default Lab', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='labassistant',
            name='license_number',
            field=models.CharField(default='LIC-000', max_length=50),
            preserve_default=False,
        ),
    ]
