# Generated by Django 5.2.5 on 2026-01-28 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_labassistant_created_at_labassistant_is_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='labassistant',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='testbooking',
            name='lab',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='app.labassistant'),
        ),
    ]
