# Generated by Django 5.2.10 on 2026-02-18 04:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_labassistant_is_active_testbooking_lab'),
    ]

    operations = [
        migrations.AddField(
            model_name='testbooking',
            name='is_report_final',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='testbooking',
            name='payment_proof',
            field=models.FileField(blank=True, null=True, upload_to='payment_proofs/'),
        ),
        migrations.AddField(
            model_name='testbooking',
            name='payment_rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testbooking',
            name='payment_status',
            field=models.CharField(choices=[('Pending Verification', 'Pending Verification'), ('Verified', 'Verified'), ('Rejected', 'Rejected')], default='Pending Verification', max_length=30),
        ),
        migrations.AddField(
            model_name='testbooking',
            name='report_file',
            field=models.FileField(blank=True, null=True, upload_to='test_reports/'),
        ),
        migrations.AddField(
            model_name='testbooking',
            name='report_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testbooking',
            name='time_slot',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='testbooking',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='testbooking',
            name='booking_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='testbooking',
            name='lab',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='app.labassistant'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testbooking',
            name='status',
            field=models.CharField(choices=[('Pending Approval', 'Pending Approval'), ('Confirmed', 'Confirmed'), ('Sample Collected', 'Sample Collected'), ('Processing', 'Processing'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending Approval', max_length=30),
        ),
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_tests', to='app.labassistant')),
            ],
        ),
        migrations.AddField(
            model_name='testbooking',
            name='lab_test',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='app.labtest'),
        ),
    ]
