# Generated by Django 5.2.10 on 2026-02-18 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_testbooking_is_report_final_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testbooking',
            name='lab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='app.labassistant'),
        ),
    ]
