# Generated by Django 5.2.10 on 2026-02-18 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_staticpage_systemsetting_labassistant_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='labassistant',
            name='payment_qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='lab_qrs/'),
        ),
    ]
