# Generated by Django 5.2.5 on 2026-02-18 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_labassistant_payment_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='testbooking',
            name='price_at_booking',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
