# Generated by Django 5.2.10 on 2026-02-18 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_testbooking_price_at_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='labreview',
            name='booking',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review', to='app.testbooking'),
        ),
    ]
