# Generated by Django 5.2.1 on 2025-06-03 08:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GetInTouch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=15)),
                ("message", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("registration_no", models.CharField(max_length=100)),
                ("duration", models.CharField(max_length=100)),
                ("total_fee", models.PositiveIntegerField()),
                ("course_name", models.CharField(max_length=100)),
                ("phone", models.PositiveIntegerField()),
                ("email", models.EmailField(max_length=254)),
                ("date", models.DateField(blank=True, null=True)),
                ("faculty_name", models.CharField(max_length=100)),
                ("pincode", models.CharField(max_length=10)),
                ("address", models.TextField()),
                (
                    "qualification",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "marital_status",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("online", models.BooleanField(blank=True, null=True)),
                ("completed_date", models.DateField(blank=True, null=True)),
                (
                    "certificate_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Receipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("course_name", models.CharField(max_length=100)),
                ("amount", models.PositiveIntegerField()),
                ("date", models.DateField()),
                ("reg_no", models.CharField(max_length=100)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StaffPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("receipt_permission", models.BooleanField(default=False)),
                ("certificate_permission", models.BooleanField(default=False)),
                ("student_permission", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
