# Generated by Django 5.2.1 on 2025-06-05 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="payment_completed",
            field=models.BooleanField(default=False),
        ),
    ]
