# Generated by Django 5.2.1 on 2025-06-21 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_constant_value"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="date_range",
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="project_title",
            field=models.TextField(blank=True, null=True),
        ),
    ]
