# Generated by Django 5.2.1 on 2025-06-24 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_student_date_range_student_project_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="account_balance",
            field=models.PositiveBigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
