# Generated by Django 5.2.1 on 2025-07-06 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0013_coursename_staffdetails"),
    ]

    operations = [
        migrations.RenameField(
            model_name="coursename",
            old_name="course_name",
            new_name="course_name",
        ),
    ]
