# Generated by Django 5.2.1 on 2025-07-07 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0014_rename_cousrse_name_coursename_course_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="staffdetails",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="staff_photo"),
        ),
    ]
