# Generated by Django 5.2.1 on 2025-07-12 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0015_staffdetails_photo"),
    ]

    operations = [
        migrations.RenameField(
            model_name="student",
            old_name="date",
            new_name="dob",
        ),
        migrations.AddField(
            model_name="student",
            name="joined_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
