# Generated by Django 5.2.11 on 2026-02-27 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_chatsession_awaiting_confirmation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='pickup_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
