# Generated by Django 5.2.9 on 2026-01-06 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('doctors', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('symptoms', models.TextField(help_text='Patient symptoms')),
                ('diagnosis', models.TextField(help_text="Doctor's diagnosis")),
                ('treatment_plan', models.TextField(help_text='Recommended treatment')),
                ('notes', models.TextField(blank=True, help_text='Additional notes', null=True)),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, help_text='°F', max_digits=4, null=True)),
                ('blood_pressure', models.CharField(blank=True, help_text='e.g., 120/80', max_length=20, null=True)),
                ('pulse_rate', models.PositiveIntegerField(blank=True, help_text='beats per minute', null=True)),
                ('respiratory_rate', models.PositiveIntegerField(blank=True, help_text='breaths per minute', null=True)),
                ('oxygen_saturation', models.DecimalField(blank=True, decimal_places=2, help_text='%', max_digits=5, null=True)),
                ('follow_up_required', models.BooleanField(default=False)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_records', to='appointments.appointment')),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_records', to='doctors.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='patients.patient')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LabReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('test_type', models.CharField(choices=[('blood', 'Blood Test'), ('urine', 'Urine Test'), ('xray', 'X-Ray'), ('mri', 'MRI'), ('ct_scan', 'CT Scan'), ('ultrasound', 'Ultrasound'), ('ecg', 'ECG'), ('other', 'Other')], max_length=20)),
                ('test_name', models.CharField(max_length=200)),
                ('test_date', models.DateField()),
                ('results', models.TextField()),
                ('file', models.FileField(blank=True, null=True, upload_to='lab_reports/')),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('medical_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_reports', to='medical_records.medicalrecord')),
            ],
            options={
                'ordering': ['-test_date'],
            },
        ),
        migrations.AddIndex(
            model_name='medicalrecord',
            index=models.Index(fields=['record_id'], name='medical_rec_record__d3f6de_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalrecord',
            index=models.Index(fields=['patient', '-created_at'], name='medical_rec_patient_2431c8_idx'),
        ),
    ]
