# Generated by Django 5.2.9 on 2026-01-06 08:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nurse_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('qualifications', models.TextField(help_text='Nursing degrees and certifications')),
                ('license_number', models.CharField(max_length=50, unique=True)),
                ('shift', models.CharField(choices=[('morning', 'Morning (6 AM - 2 PM)'), ('afternoon', 'Afternoon (2 PM - 10 PM)'), ('night', 'Night (10 PM - 6 AM)')], default='morning', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('on_leave', 'On Leave'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nurses', to='doctors.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nurse_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__first_name'],
            },
        ),
        migrations.CreateModel(
            name='NursePatientAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('nurse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_assignments', to='nurses.nurse')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nurse_assignments', to='patients.patient')),
            ],
            options={
                'ordering': ['-assigned_date'],
            },
        ),
        migrations.AddIndex(
            model_name='nurse',
            index=models.Index(fields=['nurse_id'], name='nurses_nurs_nurse_i_133540_idx'),
        ),
        migrations.AddIndex(
            model_name='nurse',
            index=models.Index(fields=['department'], name='nurses_nurs_departm_c5291a_idx'),
        ),
        migrations.AddIndex(
            model_name='nurse',
            index=models.Index(fields=['status'], name='nurses_nurs_status_e6dbcc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='nursepatientassignment',
            unique_together={('nurse', 'patient', 'assigned_date')},
        ),
    ]
