# Generated by Django 5.2.5 on 2026-02-04 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_jobseekerprofile_address_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobApplication',
        ),
    ]
