# Generated by Django 5.2.11 on 2026-02-27 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='guest_count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
